/**
 * @module types/provider
 * Provider-facing chat, tool-calling, streaming, and health schemas.
 */

import { z } from 'zod';

// ─── Tool Calling ────────────────────────────────────────────────────────────

/** Zod schema for a normalized provider tool call. */
export const ToolCallSchema = z.object({
  /** Provider-generated tool call identifier. */
  id: z.string(),
  /** Tool/function name. */
  name: z.string(),
  /** Tool/function arguments. */
  arguments: z.record(z.unknown()),
});

/** Normalized provider tool call. */
export type ToolCall = z.infer<typeof ToolCallSchema>;

/** Zod schema for a provider-visible tool definition. */
export const ToolDefinitionSchema = z.object({
  /** Tool/function name. */
  name: z.string(),
  /** Human-readable tool description. */
  description: z.string(),
  /** JSON Schema-compatible parameters object. */
  parameters: z.record(z.unknown()),
});

/** Provider-visible tool definition. */
export type ToolDefinition = z.infer<typeof ToolDefinitionSchema>;

// ─── Message ─────────────────────────────────────────────────────────────────

/** Roles used in the multi-turn chat protocol. */
export const MessageRoleSchema = z.enum([
  'system',
  'user',
  'assistant',
  'tool',
]);

/** Role within a chat conversation. */
export type MessageRole = z.infer<typeof MessageRoleSchema>;

/**
 * Zod schema for a single message in a chat conversation.
 *
 * - `role`    — who authored this message
 * - `content` — the text payload
 */
export const MessageSchema = z.discriminatedUnion('role', [
  z.object({
    /** System instruction role. */
    role: z.literal('system'),
    /** Text content of the message. */
    content: z.string(),
  }),
  z.object({
    /** User role. */
    role: z.literal('user'),
    /** Text content of the message. */
    content: z.string(),
  }),
  z.object({
    /** Assistant role. */
    role: z.literal('assistant'),
    /** Text content of the message. */
    content: z.string(),
    /** Tool calls requested by the assistant. */
    toolCalls: z.array(ToolCallSchema).optional(),
  }),
  z.object({
    /** Tool result role. */
    role: z.literal('tool'),
    /** Tool call identifier this result answers. */
    toolCallId: z.string(),
    /** Tool/function name. */
    name: z.string(),
    /** Text content of the message. */
    content: z.string(),
  }),
]);

/** A single message in a chat conversation. */
export type Message = z.infer<typeof MessageSchema>;

// ─── Chat Options ────────────────────────────────────────────────────────────

/**
 * Zod schema for options passed when initiating a chat completion.
 *
 * Required: `systemPrompt`, `messages`.
 * Optional: `temperature`, `maxTokens`.
 */
export const ChatOptionsSchema = z.object({
  /** System-level instruction prepended to the conversation. */
  systemPrompt: z.string(),
  /** Ordered list of conversation messages. */
  messages: z.array(MessageSchema),
  /** Sampling temperature (0 = deterministic, higher = more creative). */
  temperature: z.number().min(0).max(2).optional(),
  /** Maximum number of tokens to generate. */
  maxTokens: z.number().int().positive().optional(),
  /** Provider-visible tool definitions. */
  tools: z.array(ToolDefinitionSchema).optional(),
  /** Tool-choice policy. */
  toolChoice: z.enum(['auto', 'none', 'required']).optional(),
});

/** Options for a chat completion request. */
export type ChatOptions = z.infer<typeof ChatOptionsSchema>;

// ─── Token Usage ─────────────────────────────────────────────────────────────

/** Zod schema for token usage statistics returned by the provider. */
export const TokenUsageSchema = z.object({
  /** Number of tokens in the prompt. */
  promptTokens: z.number().int().nonnegative(),
  /** Number of tokens generated by the model. */
  completionTokens: z.number().int().nonnegative(),
});

/** Token usage breakdown. */
export type TokenUsage = z.infer<typeof TokenUsageSchema>;

// ─── Chat Response ───────────────────────────────────────────────────────────

/**
 * Zod schema for the complete response from a chat completion call.
 *
 * - `content` — the generated text
 * - `model`   — the model that produced it
 * - `usage`   — optional token usage breakdown
 */
export const ChatResponseSchema = z.object({
  /** The generated text content. */
  content: z.string(),
  /** Model identifier that produced this response. */
  model: z.string(),
  /** Token usage statistics (if reported by the provider). */
  usage: TokenUsageSchema.optional(),
  /** Normalized tool calls requested by the model. */
  toolCalls: z.array(ToolCallSchema).optional(),
});

/** Complete response from a chat completion. */
export type ChatResponse = z.infer<typeof ChatResponseSchema>;

// ─── Stream Chunk ────────────────────────────────────────────────────────────

/** Discriminated type tag for streaming chunks. */
export const StreamChunkTypeSchema = z.enum([
  'text',
  'tool_call',
  'done',
  'error',
]);

/** Type of a streaming chunk. */
export type StreamChunkType = z.infer<typeof StreamChunkTypeSchema>;

/**
 * Zod schema for a single chunk in a streaming response.
 *
 * - `type`    — what kind of event this chunk represents
 * - `content` — the payload (text fragment, tool call JSON, error message, etc.)
 */
export const StreamChunkSchema = z.discriminatedUnion('type', [
  z.object({
    /** Text stream chunk. */
    type: z.literal('text'),
    /** Text payload. */
    content: z.string(),
  }),
  z.object({
    /** Tool call chunk. */
    type: z.literal('tool_call'),
    /** Normalized tool call. */
    call: ToolCallSchema,
  }),
  z.object({
    /** Done marker. */
    type: z.literal('done'),
    /** Optional final text. */
    content: z.string(),
  }),
  z.object({
    /** Error marker. */
    type: z.literal('error'),
    /** Error text. */
    content: z.string(),
  }),
]);

/** A single chunk from a streaming chat response. */
export type StreamChunk = z.infer<typeof StreamChunkSchema>;

// ─── Health Status ───────────────────────────────────────────────────────────

/**
 * Zod schema for the result of a provider health check.
 *
 * - `ok`        — whether the provider is reachable and functional
 * - `latencyMs` — round-trip time in milliseconds (when healthy)
 * - `error`     — error message (when unhealthy)
 */
export const HealthStatusSchema = z.object({
  /** Whether the provider is reachable and functional. */
  ok: z.boolean(),
  /** Round-trip latency in milliseconds (present when healthy). */
  latencyMs: z.number().nonnegative().optional(),
  /** Error description (present when unhealthy). */
  error: z.string().optional(),
});

/** Result of a provider health check. */
export type HealthStatus = z.infer<typeof HealthStatusSchema>;
